apiVersion: v1
kind: Service
# Note:  If we change this to kafka, the broker won't start
# # advertised.host, advertised.port, host and port are deprecated. Exit if these properties are set.
#if [[ -n "${KAFKA_PORT-}" ]]
#   exit 2
#fi
metadata:
  name: kafka-cp-kafka-nodeport
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
# Note:  If we change this to kafka, the broker won't start
# # advertised.host, advertised.port, host and port are deprecated. Exit if these properties are set.
#if [[ -n "${KAFKA_PORT-}" ]]
#   exit 2
#fi
  - name: kafka-native
    port: 9092
    targetPort: 9092
    nodePort: 31101
  selector:
    app: cp-kafka
