apiVersion: v1
kind: Service
metadata:
  name: kafka-cp-kafka-rest-proxy
  labels:
    app: kafka-cp-kafka-rest-proxy
spec:
  type: NodePort
  ports:
  - name: kafka-cp-kafka-rest-proxy-nodeport
    port: 8082
    targetPort: 8082
    nodePort: 31100
  selector:
    app: cp-kafka-rest 
