apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
#  type: NodePort
  ports:
  - name: http-admin-app
    port: 31996
    targetPort: 31996
#    nodePort: 31996
  selector:
    app: admin
