apiVersion: v1
kind: Service
metadata:
  name: stream-cpu
  labels:
    app: stream-cpu
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - name: http-kafka
    port: 9092
    targetPort: 9092
  - name: http-schema-registry
    port: 8081
    targetPort: 8081
  - name: http-rest-proxy
    port: 8082
    targetPort: 8082
  - name: mqtt
    port: 1883
    targetPort: 1883
#  - name: http-zookeeper
#    port: 2181
#    targetPort: 2181
  selector:
    app: stream-cpu
